### ISSUE TITLE
请问如何训练第一阶段？

### ISSUE THREAD

**Issue by 66ling66** [JianghaiSCU/LightenDiffusion#1]
作者大大，我看代码好像是默认加载第一阶段的参数，请问这个阶段如何进行训练呢？

**Comment by 66ling66** [comment]
为什么代码中的下采样图像的尺寸由H.W.C-->H/8,W/8,c.论文中写的却是H/2,W/2?

**Comment by JianghaiSCU** [comment]
（1）你把第一阶段单拉出来训练就行
（2）你再仔细看看论文写的是啥

**Comment by 66ling66** [comment]
请问一下，我训练validation的时候生成的图片为什么会这样？
![image](https://github.com/user-attachments/assets/62611267-81d6-448f-a963-51f92cb679d5)
![image](https://github.com/user-attachments/assets/c564d4e6-ac82-4281-8b2b-fcc083691397)
![image](https://github.com/user-attachments/assets/83790791-14cb-4305-8707-fb94acd69460)
训练时第一阶段参数权重使用的是你开源的参数。请问一下是还有什么位置的参数需要更改吗？谢谢

**Comment by JianghaiSCU** [comment]
最开始是这样的，大概在10w个iter的时候会产生质变

**Comment by 66ling66** [comment]
好的，谢谢


---原始邮件---
发件人: &quot;Hai ***@***.***&gt;
发送时间: 2024年7月17日(周三) 晚上10:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1)




 
最开始是这样的，大概在10w个iter的时候会产生质变
 
&mdash;

**Comment by 66ling66** [comment]
https://github.com/JianghaiSCU/LightenDiffusion/blob/1724b254e921be4241f7f54e362d2b2a75f39e6b/datasets/dataset.py#L42
请问一下这个参数有什么作用？

**Comment by 66ling66** [comment]
https://github.com/JianghaiSCU/LightenDiffusion/blob/1724b254e921be4241f7f54e362d2b2a75f39e6b/datasets/dataset.py#L42
请问一下yml里的这个参数在哪里使用到了？模型好像无法接受H与W不相等的图片输入？

**Comment by JianghaiSCU** [comment]
这个参数就是训练的时候的patch大小，我们训练用的512*512，如果图像已经是这么大就不用管，如果不是就需要crop。
模型可接受h,w不等的输入只是需要满足上下采样倍率，具体可参见restoration.py

**Comment by 66ling66** [comment]
但是在restoration.py中的pad这个操作好像在加载训练数据集的时候并没有使用到，因为我同一个数据集，可以跑推理，但是跑训练的话就会在这一行报一个错误，无法cat 
https://github.com/JianghaiSCU/LightenDiffusion/blob/1724b254e921be4241f7f54e362d2b2a75f39e6b/models/unet.py#L326

**Comment by JianghaiSCU** [comment]
这些细节问题只能靠你自己解决了，训练的patch最好是512*512

**Comment by 66ling66** [comment]
嗯嗯，但是LOLv1中训练数据集高宽是400*600，这个应该如何切patch

**Comment by 66ling66** [comment]
哦哦，懂了，谢谢

**Comment by 66ling66** [comment]
能否提供一下你们用的训练集呢

**Comment by JianghaiSCU** [comment]
训练集你可以随机选择unpaired的数据，我们的训练集也是基于现有的一些数据随机组合来的，数量有点大放不下

**Comment by 66ling66** [comment]
我还有一个关于第一阶段训练的问题，如何判断CTDN已经训练的足够好了？论文中写的是训练了10w个iter，请问这10w个iter是如何得到的呢？有没有什么指标可以衡量一下，谢谢

**Comment by LiHaoyu549** [comment]
> （1）你把第一阶段单拉出来训练就行 （2）你再仔细看看论文写的是啥

请问是直接对decom.py训练吗

**Comment by LiHaoyu549** [comment]
> > （1）你把第一阶段单拉出来训练就行 （2）你再仔细看看论文写的是啥
> 
> 请问是直接对decom.py训练吗
因为看到论文训练第一阶段是说“一对低光作为输入，并且冻结diffusion的参数”，第一阶段训练编解码器和Retinex分解应该跟diffusion无关吧，只用训练decom.py，是这样吗？也可能我有误解，需要作者您解答一下，谢谢！

**Comment by d-linlin** [comment]
> 作者大大，我看代码好像是默认加载第一阶段的参数，请问这个阶段如何进行训练呢？

请问您训练成功了吗?可否请教一下如何把第一阶段单独拉出来训练

**Comment by 66ling66** [comment]
encoder 和decoder没问题，但是分解网络训练有问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月3日(周二) 上午9:08
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1)




  
作者大大，我看代码好像是默认加载第一阶段的参数，请问这个阶段如何进行训练呢？
  
请问您训练成功了吗?可否请教一下如何把第一阶段单独拉出来训练

**Comment by d-linlin** [comment]
> encoder 和decoder没问题，但是分解网络训练有问题
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月3日(周二) 上午9:08 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1) 作者大大，我看代码好像是默认加载第一阶段的参数，请问这个阶段如何进行训练呢？ 请问您训练成功了吗?可否请教一下如何把第一阶段单独拉出来训练 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

感谢您的回复！还想请问一下作者的encoder和decoder都写在decom.py文件中了吗，我有点找不到在哪里

**Comment by 66ling66** [comment]
是的，都在decom.py文件，要单独拉出来，损失函数要根据论文中的定义自己写



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月4日(周三) 下午3:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1)




  
encoder 和decoder没问题，但是分解网络训练有问题
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月3日(周二) 上午9:08 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1) 作者大大，我看代码好像是默认加载第一阶段的参数，请问这个阶段如何进行训练呢？ 请问您训练成功了吗?可否请教一下如何把第一阶段单独拉出来训练 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
感谢您的回复！还想请问一下作者的encoder和decoder都写在decom.py文件中了吗，我有点找不到在哪里

**Comment by d-linlin** [comment]
> 是的，都在decom.py文件，要单独拉出来，损失函数要根据论文中的定义自己写
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年9月4日(周三) 下午3:27 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1) encoder 和decoder没问题，但是分解网络训练有问题 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年9月3日(周二) 上午9:08 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [JianghaiSCU/LightenDiffusion] 请问如何训练第一阶段？ (Issue #1) 作者大大，我看代码好像是默认加载第一阶段的参数，请问这个阶段如何进行训练呢？ 请问您训练成功了吗?可否请教一下如何把第一阶段单独拉出来训练 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 感谢您的回复！还想请问一下作者的encoder和decoder都写在decom.py文件中了吗，我有点找不到在哪里 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

非常感谢！
