### ISSUE TITLE
train.txt

### ISSUE THREAD

**Issue by 1colorworker** [JianghaiSCU/LightenDiffusion#10]
训练数据集的tran.txt是否应该按照这种格式进行准备

/path/to/low_quality_image1.jpg /path/to/high_quality_image1.jpg
/path/to/low_quality_image2.jpg /path/to/high_quality_image2.jpg

推理阶段的txt文件该怎么准备呢

**Comment by JianghaiSCU** [comment]
train.txt的格式如下所示：/data/Image_restoration/unpaired_dataset/train/low/1.png /data/Image_restoration/unpaired_dataset/train/high/834.png；
val.txt的格式为: /data/Image_restoration/unpaired_dataset/LOLv1/low/1.png /data/Image_restoration/unpaired_dataset/LOLv1/high/1.png

**Comment by JianghaiSCU** [comment]
val.txt也可写为 /data/Image_restoration/LOLv1/low/1.png /data/Image_restoration/LOLv1/low/1.png，在infer的时候不需要normal-light image参与
