### ISSUE TITLE
How to infer

### ISSUE THREAD

**Issue by RundongCao** [JianghaiSCU/LightenDiffusion#11]
Is there any infer code or demo for low-light image enhancement? I want to test this method for some real-world cases, thanks!

**Comment by JianghaiSCU** [comment]
you can run evaluate.py

**Comment by RundongCao** [comment]
evaluate.py is not clear for inferencing a given image

**Comment by JianghaiSCU** [comment]
I think you can do it yourself, it's not difficult to prepare a demo file.
