### ISSUE TITLE
输出效果的一些问题

### ISSUE THREAD

**Issue by kfzhu1229** [JianghaiSCU/LightenDiffusion#13]
您好，我用了这个算法，接上pre-train的数据，然后试着跑了我自己照的几张720p png图像。
我发现我其中一个深圳赛格大厦的图片，处理完后大厦的窗子全是模糊的。我推测是这个算法转Latent Space时候把原图、1/4分辨率、1/16分辨率等的莫尔纹效应全部混合起来了所以窗子轮廓全部丢失了。我抽了几张latent在diffusion前面的图片也有这个问题。您看看是不是这个算法的一个根本的小缺陷
再就是我发现现在的结果处理出来总是偏黄绿，大部分照片还好，有的室内的照片色差有点严重。这个我看是不是Training能解决的问题。现在Training我跑不起来，各种各样环节的维度不匹配
其它图片起效果的时候还是很好用的

![seg](https://github.com/user-attachments/assets/0d4afff1-497d-4fb9-a5fe-27a390a819d5)

**Comment by JianghaiSCU** [comment]
为了实现unsupervised的LLIE我们采用latent分解的方式，这种方式确实会造成细节丢失的问题，这是无可避免的；黄绿的问题应该是我们的训练集里面图像分布的问题，应该是可以通过重新训练解决的。
