### ISSUE TITLE
On File Missing

### ISSUE THREAD

**Issue by jacksonz0610** [JianghaiSCU/LightenDiffusion#14]
Could you please upload '/data/Image_restoration/LSRW_dataset/unpaired_train.txt'? I couldn't find this file for unsupervised training. Thank you so much.

**Comment by kfzhu1229** [comment]
It's answered in Chinese in Issue 10.
Text file needs to have pairs of low and high separated by a spacebar:
/data/Image_restoration/LOLv1/low/1.png /data/Image_restoration/LOLv1/high/1.png

**Comment by thelin1** [comment]
> 您能否上传 '/data/Image_restoration/LSRW_dataset/unpaired_train.txt'我找不到用于无监督训练的此文件。非常感谢。
Hello, have you solved your problem? I also encountered the same problem when I reproduced this code, could you please give me some guidance
