### ISSUE TITLE
Issue for evaluation

### ISSUE THREAD

**Issue by lastbasket** [JianghaiSCU/LightenDiffusion#2]
Seems like x_cond only uses the first three-channel input (low-light)

https://github.com/JianghaiSCU/LightenDiffusion/blob/1724b254e921be4241f7f54e362d2b2a75f39e6b/models/restoration.py#L27
https://github.com/JianghaiSCU/LightenDiffusion/blob/1724b254e921be4241f7f54e362d2b2a75f39e6b/models/restoration.py#L34

**Comment by JianghaiSCU** [comment]
Yes, we only use the low-light image as condition during inference.
