### ISSUE TITLE
Data loading error

### ISSUE THREAD

**Issue by JokerHYX-719** [JianghaiSCU/LightenDiffusion#6]
After the data is loaded, the concat at line 325 of unet.py will indicate that the tensor size is wrong and whether it is a problem with the unpaired_train.txt
[unpaired_train.txt](https://github.com/user-attachments/files/16386332/unpaired_train.txt)

**Comment by JianghaiSCU** [comment]
I do not understand your question.

**Comment by JianghaiSCU** [comment]
I don't exactly get your question.

**Comment by olex-ui** [comment]
![image](https://github.com/user-attachments/assets/5da722db-94ee-4956-b17b-86ac2ab3f4dc)
Hello,I have the same question.The tensor sizes are inconsistent when the size of the input images are 400x600.I wonder if there is a lack of crop operation on the training images.
