### ISSUE TITLE
请问您的unpaired_train.txt能发出来一下吗，想参考一下

### ISSUE THREAD

**Issue by JokerHYX-719** [JianghaiSCU/LightenDiffusion#9]

**Comment by 66ling66** [comment]
自己写个脚本，把图片路径写进txt文件或者json文件都可以

**Comment by JianghaiSCU** [comment]
train.txt的格式如下所示：/data/Image_restoration/unpaired_dataset/train/low/1.png /data/Image_restoration/unpaired_dataset/train/high/834.png；
val.txt的格式为: /data/Image_restoration/LOLv1/low/1.png /data/Image_restoration/LOLv1/high/1.png
